### model
model_name_or_path: meta-llama/Llama-3.2-1B
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z3_config.json
flash_attn: fa2

### dataset
dataset: wikitext
# template: llama3
template: empty
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama/full/midtrain_wikitext_dispersion_infonce_l2_new_hparams
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb
run_name: llama-wiki-pretrain-dispersion-infonce_l2-new-hparams

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 64
learning_rate: 5.0e-5
# max_grad_norm: 10.0
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
# warmup_steps: 50
# weight_decay: 0.01 
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

### dispersion loss
dispersion: "infonce_l2"  # or "hinge", "covariance"
dispersion_coeff: 0.5
dispersion_loc: "last"  # or "all"
tau_infonce_l2: 0.5
tau_infonce_cos: 0.5

### LM evaluation
lmeval_enabled: true
lmeval_tasks: "paloma_wikitext_103,lambada,mmlu,medmcqa,wikitext"  # Choose your tasks
# lmeval_num_fewshot: 5
lmeval_num_fewshot: 1
# lmeval_max_eval_samples: 200
lmeval_max_eval_samples: 200
lmeval_eval_at_begin: true
lmeval_eval_at_end: true
lmeval_every_n_steps: 100  # Set to null to disable interval evaluation
lmeval_save_on_eval: true