### model
model_name_or_path: meta-llama/Llama-3.2-1B
trust_remote_code: true

### method
stage: pt
do_train: true
# finetuning_type: lora
# lora_target: all
finetuning_type: full
# deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
flash_attn: fa2

### dataset
dataset: wikitext
# template: llama3 # do not use template for pretraining
template: empty
cutoff_len: 8192
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama/full/midtrain_wikitext_lr1e-4_6_epoch
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
# report_to: none
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: llama-wiki-midtrain

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 256
learning_rate: 1.0e-4
# per_device_train_batch_size: 3
# gradient_accumulation_steps: 86
# learning_rate: 1e-6
# max_grad_norm: 10.0
num_train_epochs: 6
lr_scheduler_type: cosine
# warmup_ratio: 0.03
warmup_steps: 50
weight_decay: 0.01
bf16: true
ddp_timeout: 180000000

### eval
# eval_dataset: wikitext
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

### LM evaluation
lmeval_enabled: true
lmeval_tasks: "paloma_wikitext_103,lambada,mmlu,medmcqa,wikitext"  # Choose your tasks
# lmeval_num_fewshot: 5
lmeval_num_fewshot: 5
# lmeval_max_eval_samples: 200
lmeval_max_eval_samples: 200
lmeval_eval_at_begin: true
lmeval_eval_at_end: true
lmeval_every_n_steps: 100  # Set to null to disable interval evaluation
lmeval_save_on_eval: false